include: package:flutter_lints/flutter.yaml

linter:
  rules:
    // ignore_for_file: prefer_const_constructors, prefer_typing_uninitialized_variables, non_constant_identifier_names, prefer_interpolation_to_compose_strings
